#!/usr/bin/env bash
set -euo pipefail

# Creates local (gitignored) config for WEB production deploy.
#
# Output:
#   .traxettle/web-prod.env
#
# Usage:
#   bash scripts/web-deployment/configure-prod.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUT_DIR="${REPO_ROOT}/.traxettle"
OUT_FILE="${OUT_DIR}/web-prod.env"

mkdir -p "$OUT_DIR"

escape_sq() {
  printf "%s" "$1" | sed "s/'/'\\\\''/g"
}

prompt() {
  local var="$1"
  local label="$2"
  local def="${3:-}"

  local val=""
  read -r -p "${label}${def:+ [${def}]}: " val
  val="${val:-$def}"
  printf -v "$var" "%s" "$val"
}

echo ""
echo "═══════════════════════════════════════════════"
echo "  Traxettle — Configure WEB PRODUCTION deploy"
echo "═══════════════════════════════════════════════"
echo ""
echo "This saves your production web deploy config locally in:"
echo "  $OUT_FILE"
echo ""

prompt GCP_PROJECT_ID "GCP project id" "traxettle-prod"
prompt HOSTING_SITE_ID "Firebase Hosting site id" "traxettle-prod"
prompt NEXT_PUBLIC_API_URL "Production API URL (Cloud Run URL or custom domain)" ""

echo ""
echo "Now enter Firebase Web App config values (Firebase Console → Project Settings → Your apps → Web app)."
prompt NEXT_PUBLIC_FIREBASE_API_KEY "Firebase apiKey" ""
prompt NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN "Firebase authDomain" ""
prompt NEXT_PUBLIC_FIREBASE_PROJECT_ID "Firebase projectId" "traxettle-prod"
prompt NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET "Firebase storageBucket" "traxettle-prod.firebasestorage.app"
prompt NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID "Firebase messagingSenderId" ""
prompt NEXT_PUBLIC_FIREBASE_APP_ID "Firebase appId" ""
prompt NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID "Firebase measurementId (optional)" ""

cat > "$OUT_FILE" <<EOF
# Generated by scripts/web-deployment/configure-prod.sh on $(date)
# Never commit this file. It is gitignored.

GCP_PROJECT_ID='$(escape_sq "$GCP_PROJECT_ID")'
REGION='us-central1'
WEB_SERVICE_NAME='traxettle-web-prod'
HOSTING_SITE_ID='$(escape_sq "$HOSTING_SITE_ID")'

NEXT_PUBLIC_API_URL='$(escape_sq "$NEXT_PUBLIC_API_URL")'
NEXT_PUBLIC_APP_ENV='production'
NEXT_PUBLIC_FIREBASE_API_KEY='$(escape_sq "$NEXT_PUBLIC_FIREBASE_API_KEY")'
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN='$(escape_sq "$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN")'
NEXT_PUBLIC_FIREBASE_PROJECT_ID='$(escape_sq "$NEXT_PUBLIC_FIREBASE_PROJECT_ID")'
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET='$(escape_sq "$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET")'
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID='$(escape_sq "$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID")'
NEXT_PUBLIC_FIREBASE_APP_ID='$(escape_sq "$NEXT_PUBLIC_FIREBASE_APP_ID")'
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID='$(escape_sq "$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID")'
EOF

echo ""
echo "Saved: $OUT_FILE"
echo "You can now deploy production web with:"
echo "  bash scripts/web-deployment/deploy-web-prod.sh"
echo ""

