#!/usr/bin/env bash
set -euo pipefail

# Traxettle RevenueCat config generator (layman-friendly)
#
# Creates gitignored files:
#   rc_local.properties
#   rc_staging.properties
#   rc_production.properties
#
# Usage:
#   bash scripts/revenuecat/configure.sh local
#   bash scripts/revenuecat/configure.sh staging
#   bash scripts/revenuecat/configure.sh production

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

ENV_RAW="${1:-}"
if [[ -z "$ENV_RAW" ]]; then
  echo "Usage: $0 <local|staging|production>"
  exit 1
fi

case "$ENV_RAW" in
  local|staging|production) ENV="$ENV_RAW" ;;
  prod) ENV="production" ;;
  *) echo "Invalid environment: $ENV_RAW (use: local|staging|production)" ; exit 1 ;;
esac

OUT_FILE="${ROOT_DIR}/rc_${ENV}.properties"
TEMPLATE="${ROOT_DIR}/rc_env.properties.example"

if [[ -f "$OUT_FILE" ]]; then
  read -r -p "rc_${ENV}.properties already exists. Overwrite? (y/n): " yn
  case "${yn:-n}" in
    y|Y) ;;
    *) echo "Keeping existing: $OUT_FILE" ; exit 0 ;;
  esac
fi

if [[ ! -f "$TEMPLATE" ]]; then
  echo "Missing template: $TEMPLATE"
  exit 1
fi

echo ""
echo "═══════════════════════════════════════════════"
echo "  Traxettle — RevenueCat Config ($ENV)"
echo "═══════════════════════════════════════════════"
echo ""
echo "You will be asked for values from RevenueCat Dashboard → API Keys."
echo "Tip: Apple key starts with appl_ and Google key starts with goog_."
echo ""

read -r -p "RevenueCat Apple public key (appl_...) : " APPLE_KEY
read -r -p "RevenueCat Google public key (goog_...) : " GOOGLE_KEY
read -r -p "RevenueCat Entitlement ID [pro] : " ENTITLEMENT_ID
ENTITLEMENT_ID="${ENTITLEMENT_ID:-pro}"
read -r -p "RevenueCat Offering ID [default] : " OFFERING_ID
OFFERING_ID="${OFFERING_ID:-default}"
read -r -p "RevenueCat Webhook Secret (any string) : " WEBHOOK_SECRET
read -r -p "RevenueCat Secret API key (optional, press Enter to skip) : " SECRET_API_KEY

mkdir -p "$(dirname "$OUT_FILE")"

cat > "$OUT_FILE" <<EOF
# Generated by scripts/revenuecat/configure.sh on $(date)
# Environment: $ENV
#
# Never commit this file. It is gitignored.

RC_REVENUECAT_APPLE_PUBLIC_KEY=${APPLE_KEY}
RC_REVENUECAT_GOOGLE_PUBLIC_KEY=${GOOGLE_KEY}
RC_REVENUECAT_PRO_ENTITLEMENT_ID=${ENTITLEMENT_ID}
RC_REVENUECAT_OFFERING_ID=${OFFERING_ID}
RC_REVENUECAT_WEBHOOK_SECRET=${WEBHOOK_SECRET}
RC_REVENUECAT_SECRET_API_KEY=${SECRET_API_KEY}
EOF

echo ""
echo "Saved: $OUT_FILE"
echo "Next (optional verification):"
echo "  source scripts/revenuecat/load-rc-config.sh ${ENV} && echo OK"
echo ""

