import type { Platform, WorkflowStep } from '@/types';

export function revenueCatUtilitySteps(platform: Platform): WorkflowStep[] {
  return [
    {
      id: 'u-rc-create-project',
      platform,
      environment: 'utility',
      section: 'RevenueCat',
      title: 'Create RevenueCat project and apps (Android + iOS)',
      whyThisMatters:
        'Traxettle uses RevenueCat for in-app purchases. Without RevenueCat project/apps, Pro purchases won’t work.',
      kind: 'action',
      skippable: false,
      instructions: [
        'In RevenueCat Dashboard:',
        '1) Create a new Project (name: Traxettle)',
        '2) Add Android app:',
        '   - Package name: com.traxettle.app',
        '3) Add iOS app:',
        '   - Bundle ID: com.traxettle.app',
        'Note: Store linking (Google Play / App Store Connect) is needed for real purchases, but you can still setup keys + webhook now.',
      ],
      scripts: [{ label: 'Open RevenueCat Dashboard (manual)', command: 'echo "Open: https://app.revenuecat.com/"' }],
      expected: ['You can see Traxettle project with Android + iOS apps inside RevenueCat.'],
    },
    {
      id: 'u-rc-link-stores',
      platform,
      environment: 'utility',
      section: 'RevenueCat',
      title: 'Link RevenueCat to Google Play + App Store Connect (for real purchases)',
      whyThisMatters:
        'Real purchases require RevenueCat to be connected to store backends so it can validate and sync products.',
      kind: 'action',
      skippable: false,
      instructions: [
        'In RevenueCat Dashboard → Project → Apps:',
        '1) For Google Play app:',
        '   - Link a Google Play service account (Play Console → Setup → API access)',
        '2) For iOS app:',
        '   - Link App Store Connect (you may need an API key / issuer ID / key ID)',
        '   - Add the App Store Connect shared secret if required',
        '',
        'If you don’t have store accounts yet, you can skip linking for now, but do not expect real purchases to work.',
      ],
      expected: ['RevenueCat shows store connections as active (or you have planned to complete it later).'],
    },
    {
      id: 'u-rc-entitlements-offerings',
      platform,
      environment: 'utility',
      section: 'RevenueCat',
      title: 'Create Entitlement + Offering (required by the app)',
      whyThisMatters: 'The app expects a Pro entitlement and a default offering.',
      kind: 'action',
      skippable: false,
      instructions: [
        'In RevenueCat Dashboard:',
        '1) Create an Entitlement:',
        '   - Identifier: pro',
        '2) Create an Offering:',
        '   - Identifier: default',
        '   - Set it as Current',
        '3) Add packages/products to the Offering (your developer can help if needed).',
      ],
      expected: ['Entitlement “pro” exists.', 'Offering “default” exists and is Current.'],
    },
    {
      id: 'u-rc-api-keys',
      platform,
      environment: 'utility',
      section: 'RevenueCat',
      title: 'Collect RevenueCat keys + webhook secret',
      whyThisMatters:
        'Mobile/Web builds need RevenueCat public SDK keys. The API needs the webhook secret to accept entitlement updates.',
      kind: 'action',
      skippable: false,
      instructions: [
        'In RevenueCat Dashboard → Project → API Keys:',
        '1) Copy Apple public SDK key (starts with appl_)',
        '2) Copy Google public SDK key (starts with goog_)',
        '3) Decide a Webhook Secret (any long random string)',
        'You will enter these in the next step (configure script).',
      ],
      expected: ['You have appl_… key, goog_… key, and a webhook secret ready.'],
    },
    {
      id: 'u-rc-config-files',
      platform,
      environment: 'utility',
      section: 'RevenueCat',
      title: 'Create rc_<env>.properties files (no manual editing)',
      whyThisMatters:
        'Build and deploy scripts load RevenueCat values from gitignored rc_<env>.properties files.',
      kind: 'action',
      skippable: false,
      instructions: [
        'Run the configure script once per environment you plan to use.',
        'Use the SAME Entitlement ID and Offering ID that you created in RevenueCat (defaults: pro / default).',
      ],
      scripts: [
        { label: 'Configure local', command: 'bash scripts/revenuecat/configure.sh local' },
        { label: 'Configure staging', command: 'bash scripts/revenuecat/configure.sh staging' },
        { label: 'Configure production', command: 'bash scripts/revenuecat/configure.sh production' },
      ],
      expected: ['rc_local.properties, rc_staging.properties, rc_production.properties exist (gitignored).'],
    },
    {
      id: 'u-rc-webhook-setup',
      platform,
      environment: 'utility',
      section: 'RevenueCat',
      title: 'Configure RevenueCat webhook to call your API',
      whyThisMatters:
        'RevenueCat updates user entitlements by calling your API webhook endpoint.',
      kind: 'action',
      skippable: false,
      instructions: [
        'You will set a webhook URL for EACH environment (local / staging / production).',
        '',
        'Webhook URLs:',
        '- Local: http://localhost:3001/api/billing/revenuecat/webhook',
        '- Staging: <YOUR_STAGING_API_URL>/api/billing/revenuecat/webhook',
        '- Production: <YOUR_PROD_API_URL>/api/billing/revenuecat/webhook',
        '',
        'Webhook secret header:',
        '- Recommended header: X-Webhook-Secret',
        '- Value: the same secret you configured in rc_<env>.properties and API deploy config',
        '',
        'If the RevenueCat UI only supports an Authorization header, set Authorization to the same secret (this API accepts multiple header names).',
      ],
      expected: ['RevenueCat webhook is configured for the correct environment and points to the correct API URL.'],
    },
    {
      id: 'u-rc-webhook-test',
      platform,
      environment: 'utility',
      section: 'RevenueCat',
      title: 'Test the webhook locally (smoke test)',
      whyThisMatters: 'Confirms your webhook secret + endpoint wiring works before you rely on real purchases.',
      kind: 'verify',
      skippable: false,
      instructions: [
        '1) Start local mode (API must be running on port 3001):',
        '   - sh scripts/local-dev/02_emulator_web.sh   OR',
        '   - sh scripts/local-dev/01_emulator_mobile.sh',
        '2) Then run the smoke test script below (it sends a fake RevenueCat webhook).',
      ],
      scripts: [{ label: 'Smoke webhook (local)', command: 'bash scripts/revenuecat/smoke-webhook.sh' }],
      expected: ['The script prints “Smoke webhook succeeded.”'],
    },
  ];
}
