FROM node:24-alpine
WORKDIR /app

COPY . .

RUN corepack enable \
 && apk add --no-cache bash \
 && npx @microsoft/rush@5.167.0 update --bypass-policy \
 && npx @microsoft/rush@5.167.0 build --to @traxettle/web

WORKDIR /app/apps/web
ENV NODE_ENV=production
ENV PORT=8080
EXPOSE 8080
CMD ["npm", "run", "start", "--", "-p", "8080", "-H", "0.0.0.0"]
