RC_REVENUECAT_GOOGLE_PUBLIC_KEY=goog_MjrodNDQMyNIDBuwFWkkCDaZdvO

RC_REVENUECAT_WEBHOOK_SECRET=traxettle-production-08fc96e63f2522dd13b74373ea86e309b7d790b8c89feb128d8af56d003be2b3
RC_REVENUECAT_SECRET_API_KEY=

RC_REVENUECAT_APPLE_PUBLIC_KEY=appl_CHANGE_ME

RC_REVENUECAT_PRO_ENTITLEMENT_ID=traxettle-pro

RC_REVENUECAT_OFFERING_ID=traxettle-default