import type { WorkflowStep } from '@/types';

export const mobileSteps: WorkflowStep[] = [
  // Prerequisites Section - Must be completed before any environment setup
  {
    id: 'm-prerequisite-android-keystore',
    platform: 'mobile',
    environment: 'local', // Show in all environments but mark as local
    title: '🔐 Android Keystore Setup (Prerequisite)',
    whyThisMatters: 'Android keystore is required for app signing and Firebase SHA-1 configuration.',
    kind: 'action',
    skippable: true,
    instructions: [
      'This prerequisite sets up Android app signing:',
      '  - Creates release keystore for app signing',
      '  - Generates SHA-1 fingerprints for Firebase',
      '  - Configures Gradle for production builds',
      '',
      'Run the automated setup script:',
      '  bash common/scripts/doctor-keystore.sh',
      '',
      'The script will guide you through:',
      '  - Creating traxettle-release-key.keystore',
      '  - Adding SHA-1 to Firebase projects',
      '  - Updating build.gradle configuration',
      '  - Backup and recovery procedures',
    ],
    scripts: [
      {
        label: 'Run Android keystore setup',
        command: 'bash common/scripts/doctor-keystore.sh',
      },
      {
        label: 'Check keystore exists',
        command: 'ls -la apps/mobile/android/app/traxettle-release-key.keystore || echo "Run keystore setup first"',
      },
    ],
  },
  {
    id: 'm-prerequisite-apple-team',
    platform: 'mobile',
    environment: 'local', // Show in all environments but mark as local
    title: '🍎 Apple Team ID Setup (Prerequisite)',
    whyThisMatters: 'Apple Team ID is required for iOS app development and Firebase configuration.',
    kind: 'action',
    skippable: true,
    instructions: [
      'This prerequisite sets up iOS development:',
      '  - Finds your Apple Developer Team ID',
      '  - Adds Team ID to Firebase projects',
      '  - Sets up iOS certificates and provisioning',
      '',
      'Run the automated setup script:',
      '  bash common/scripts/doctor-apple-team.sh',
      '',
      'The script will guide you through:',
      '  - Finding Team ID in Developer Portal',
      '  - Adding Team ID to all Firebase projects',
      '  - Downloading updated iOS config files',
      '  - Verifying bundle ID consistency',
    ],
    scripts: [
      {
        label: 'Run Apple Team ID setup',
        command: 'bash common/scripts/doctor-apple-team.sh',
      },
      {
        label: 'Check iOS config exists',
        command: 'ls -la apps/mobile/GoogleService-Info.plist || echo "Run Apple Team ID setup first"',
      },
    ],
  },
  {
    id: 'm-prerequisite-system-check',
    platform: 'mobile',
    environment: 'local', // Show in all environments but mark as local
    title: '🔧 System Requirements Check',
    whyThisMatters: 'Ensure your system has all required tools for mobile development.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Verify system requirements:',
      '  - Node.js 18+ installed',
      '  - React Native CLI installed',
      '  - Android Studio with SDK',
      '  - Xcode (for iOS development)',
      '  - Git installed',
      '',
      'Check development tools:',
      '  - npm or yarn package manager',
      '  - Metro bundler working',
      '  - Emulator/simulator running',
    ],
    scripts: [
      {
        label: 'Check Node.js version',
        command: 'node --version',
      },
      {
        label: 'Check React Native CLI',
        command: 'npx react-native --version || echo "React Native CLI not found"',
      },
      {
        label: 'Check Android SDK',
        command: 'echo $ANDROID_HOME || echo "Android SDK not configured"',
      },
      {
        label: 'Check Git',
        command: 'git --version',
      },
    ],
    expected: ['Node.js 18+', 'React Native CLI', 'Android SDK configured', 'Git available'],
  },

  // Local Development Section
  {
    id: 'm-local-action-system',
    platform: 'mobile',
    environment: 'local',
    title: 'Check system requirements',
    whyThisMatters: 'Node.js v24+, Git, and basic tools are required for all development and builds.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Install Node.js v24+ (required by rush.json >=24.11.1).',
      'Install Git (for version control).',
      'Install curl/wget (recommended for downloads).',
    ],
    scripts: [
      {
        label: 'Check Node version',
        command: 'node --version',
      },
      {
        label: 'Check Git',
        command: 'git --version',
      },
      {
        label: 'Check curl',
        command: 'curl --version',
      },
    ],
  },
  {
    id: 'm-local-verify-system',
    platform: 'mobile',
    environment: 'local',
    title: 'Verify system requirements',
    whyThisMatters: 'Ensures your OS and basic tools meet the minimum requirements.',
    kind: 'verify',
    skippable: false,
    instructions: ['Run the doctor script to verify system requirements.'],
    scripts: [
      {
        label: 'Run system checks',
        command: 'node common/scripts/doctor.js local --non-interactive',
      },
    ],
    expected: ['Node.js v24+ detected', 'Git installed', 'curl/wget available'],
  },

  {
    id: 'm-local-action-package-managers',
    platform: 'mobile',
    environment: 'local',
    title: 'Install package managers',
    whyThisMatters: 'npm, pnpm, and Rush are required to manage monorepo dependencies.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Install npm (comes with Node.js).',
      'Install pnpm (required by Rush).',
      'Verify Rush is working.',
    ],
    scripts: [
      {
        label: 'Check npm',
        command: 'npm --version',
      },
      {
        label: 'Check pnpm',
        command: 'pnpm --version',
      },
      {
        label: 'Check Rush',
        command: 'node common/scripts/install-run-rush.js --version',
      },
    ],
  },
  {
    id: 'm-local-action-install-deps',
    platform: 'mobile',
    environment: 'local',
    title: 'Install monorepo dependencies',
    whyThisMatters: 'All apps and scripts depend on Rush installing packages correctly.',
    kind: 'action',
    skippable: false,
    instructions: ['From the repo root, run the install command and wait for it to finish.'],
    scripts: [{ label: 'Install dependencies', command: 'rush install' }],
  },

  {
    id: 'm-local-action-firebase-local',
    platform: 'mobile',
    environment: 'local',
    title: 'Set up Firebase for local development',
    whyThisMatters: 'Firebase is used for authentication, database, and storage in local development.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Create Firebase project: traxettle-test (or use existing)',
      'Enable Authentication (Email/Password, Google)',
      'Enable Firestore Database',
      'Enable Storage (for files/images)',
      'Download service account key to apps/api/traxettle-test-service-account.json',
      'Download Android config to apps/mobile/android/app/google-services.json',
      'Download iOS config to apps/mobile/GoogleService-Info.plist',
    ],
    scripts: [
      {
        label: 'Check Firebase service account',
        command: 'ls -la apps/api/traxettle-test-service-account.json',
      },
      {
        label: 'Check Android Firebase config',
        command: 'ls -la apps/mobile/android/app/google-services.json',
      },
      {
        label: 'Check iOS Firebase config',
        command: 'ls -la apps/mobile/GoogleService-Info.plist',
      },
    ],
  },
  {
    id: 'm-local-verify-firebase-local',
    platform: 'mobile',
    environment: 'local',
    title: 'Verify Firebase local setup',
    whyThisMatters: 'Ensures Firebase configuration files are in place for local development.',
    kind: 'verify',
    skippable: false,
    instructions: ['Run the doctor script to verify Firebase configuration.'],
    scripts: [
      {
        label: 'Verify Firebase',
        command: 'node common/scripts/doctor.js local --non-interactive',
      },
    ],
    expected: ['Firebase service account key found', 'Android Firebase config found', 'iOS Firebase config found'],
  },

  {
    id: 'm-local-action-android-sdk',
    platform: 'mobile',
    environment: 'local',
    title: 'Set up Android SDK',
    whyThisMatters: 'Android SDK and Java are required for building Android releases.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Install Android Studio (includes Android SDK).',
      'Set ANDROID_HOME or ANDROID_SDK_ROOT environment variable.',
      'Install Java (JDK) for Android builds.',
      'Accept Android SDK licenses.',
    ],
    scripts: [
      {
        label: 'Check Android SDK',
        command: 'echo $ANDROID_HOME && ls -la "$ANDROID_HOME"',
      },
      {
        label: 'Check Java',
        command: 'java -version',
      },
    ],
  },
  {
    id: 'm-local-verify-android-sdk',
    platform: 'mobile',
    environment: 'local',
    title: 'Verify Android SDK setup',
    whyThisMatters: 'Confirms Android build tools are properly configured.',
    kind: 'verify',
    skippable: false,
    instructions: ['Run the doctor script to verify Android SDK and Java.'],
    scripts: [
      {
        label: 'Verify Android setup',
        command: 'node common/scripts/doctor.js local --non-interactive',
      },
    ],
    expected: ['Android SDK found', 'Java available'],
  },

  {
    id: 'm-local-action-keystore',
    platform: 'mobile',
    environment: 'local',
    title: 'Create Android keystore',
    whyThisMatters: 'Keystore is required for signing Android release builds.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Generate Android release keystore with password',
      'Create gradle.properties.local with keystore details',
      'Store keystore password and alias securely',
      'Never commit keystore files to version control',
    ],
    scripts: [
      {
        label: 'Check Android keystore',
        command: 'ls -la apps/mobile/android/app/traxettle-release-key.keystore',
      },
      {
        label: 'Check gradle properties',
        command: 'ls -la apps/mobile/android/gradle.properties.local',
      },
    ],
  },
  {
    id: 'm-local-action-keystore-sha',
    platform: 'mobile',
    environment: 'local',
    title: 'Generate SHA-1 fingerprint',
    whyThisMatters: 'SHA-1 fingerprint is required for Firebase Android app configuration.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Generate SHA-1 fingerprint from keystore',
      'Copy SHA-1 for Firebase configuration',
      'Store SHA-1 in secure location for reference',
    ],
    scripts: [
      {
        label: 'Generate SHA-1 from keystore',
        command: 'cd apps/mobile/android/app && keytool -list -v -keystore traxettle-release-key.keystore -alias traxettle',
      },
    ],
  },

  {
    id: 'm-local-action-dev-server',
    platform: 'mobile',
    environment: 'local',
    title: 'Start development server',
    whyThisMatters: 'Run the mobile app locally to test before deployment.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Start the Expo development server',
      'Open the app in Expo Go or build locally',
      'Test basic functionality',
    ],
    scripts: [
      {
        label: 'Start mobile dev server',
        command: 'cd apps/mobile && npx expo start',
      },
    ],
  },
  {
    id: 'm-local-verify-dev-server',
    platform: 'mobile',
    environment: 'local',
    title: 'Verify development server',
    whyThisMatters: 'Confirms the mobile app runs correctly in development mode.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Open Expo development server in browser',
      'Test on device/simulator',
      'Verify Firebase connection works',
    ],
    expected: ['Development server running', 'App loads on device', 'Firebase connection working'],
  },

  {
    id: 'm-local-action-final',
    platform: 'mobile',
    environment: 'local',
    title: 'Final verification',
    whyThisMatters: 'Run comprehensive checks to ensure local environment is ready.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Run the full doctor script',
      'Fix any remaining issues',
      'Test mobile app locally',
    ],
    scripts: [
      {
        label: 'Run full doctor check',
        command: 'node common/scripts/doctor.js local',
      },
    ],
  },

  {
    id: 'm-staging-action-firebase-project',
    platform: 'mobile',
    environment: 'staging',
    title: 'Create Firebase staging project',
    whyThisMatters: 'Staging requires a separate Firebase project to test without affecting production data.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Go to Firebase Console: https://console.firebase.google.com/',
      'Click "Add project" and name it: traxettle-staging',
      'Enable Google Analytics (optional)',
      'Click "Create project" and wait for provisioning',
      'Note the Project ID (should be: traxettle-staging)',
    ],
    scripts: [
      {
        label: 'Check Firebase project ID',
        command: 'echo "Expected Firebase project ID: traxettle-staging"',
      },
    ],
  },
  {
    id: 'm-staging-action-firebase-services',
    platform: 'mobile',
    environment: 'staging',
    title: 'Enable Firebase services',
    whyThisMatters: 'Authentication, Database, and Storage are required for the app to function.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-staging project, enable Authentication:',
      '  - Go to Authentication → Sign-in method',
      '  - Enable Email/Password provider',
      '  - Enable Google provider (requires OAuth consent screen)',
      '',
      'Enable Firestore Database:',
      '  - Go to Firestore Database → Create database',
      '  - Choose Start in test mode (for now)',
      '  - Select a location (choose nearest to your users)',
      '',
      'Enable Storage:',
      '  - Go to Storage → Get started',
      '  - Choose Start in test mode (for now)',
      '  - Use default security rules (will update later)',
    ],
    scripts: [
      {
        label: 'Check Firebase services enabled',
        command: 'echo "Verify Authentication, Firestore, and Storage are enabled in Firebase Console"',
      },
    ],
  },
  {
    id: 'm-staging-action-firebase-android',
    platform: 'mobile',
    environment: 'staging',
    title: 'Add Android app to Firebase',
    whyThisMatters: 'Android app needs Firebase configuration to connect to services.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-staging Firebase project:',
      '  - Go to Project Settings → Your Apps',
      '  - Click Android icon to add Android app',
      '  - Package name: com.traxettle.app (from app.json)',
      '  - Download google-services.json',
      '  - Save to: apps/mobile/android/app/google-services.json',
      '  - This will overwrite local config (that\'s OK for staging)',
    ],
    scripts: [
      {
        label: 'Check Android Firebase config',
        command: 'ls -la apps/mobile/android/app/google-services.json',
      },
    ],
  },
  {
    id: 'm-staging-action-firebase-ios',
    platform: 'mobile',
    environment: 'staging',
    title: 'Add iOS app to Firebase',
    whyThisMatters: 'iOS app needs Firebase configuration to connect to services.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-staging Firebase project:',
      '  - Go to Project Settings → Your Apps',
      '  - Click iOS icon to add iOS app',
      '  - Bundle ID: com.traxettle.app (from app.json)',
      '  - Download GoogleService-Info.plist',
      '  - Save to: apps/mobile/GoogleService-Info.plist',
      '  - This will overwrite local config (that\'s OK for staging)',
    ],
    scripts: [
      {
        label: 'Check iOS Firebase config',
        command: 'ls -la apps/mobile/GoogleService-Info.plist',
      },
    ],
  },
  {
    id: 'm-staging-action-firebase-sha',
    platform: 'mobile',
    environment: 'staging',
    title: 'Add SHA-1 to Firebase Android app',
    whyThisMatters: 'SHA-1 fingerprint is required for Google Sign-In and release builds.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Get SHA-1 from your keystore (if not already done):',
      '  cd apps/mobile/android/app',
      '  keytool -list -v -keystore traxettle-release-key.keystore -alias traxettle',
      '',
      'In Firebase Console (traxettle-staging):',
      '  - Go to Project Settings → Your Apps → Android app',
      '  - Scroll down to "SHA certificate fingerprints"',
      '  - Click "Add certificate"',
      '  - Paste your SHA-1 fingerprint',
      '  - Save changes',
    ],
    scripts: [
      {
        label: 'Generate SHA-1 from keystore',
        command: 'cd apps/mobile/android/app && keytool -list -v -keystore traxettle-release-key.keystore -alias traxettle | grep SHA1',
      },
    ],
  },
  {
    id: 'm-staging-action-firebase-service-account',
    platform: 'mobile',
    environment: 'staging',
    title: 'Create Firebase service account',
    whyThisMatters: 'Service account key allows backend to access Firebase services.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-staging Firebase project:',
      '  - Go to Project Settings → Service accounts',
      '  - Click "Generate new private key"',
      '  - Select JSON key type',
      '  - Click "Create" and download the JSON file',
      '  - Save as: apps/api/traxettle-staging-service-account.json',
      '  - Never commit this file to version control',
    ],
    scripts: [
      {
        label: 'Check staging service account',
        command: 'ls -la apps/api/traxettle-staging-service-account.json',
      },
    ],
  },
  {
    id: 'm-staging-action-gradle-config',
    platform: 'mobile',
    environment: 'staging',
    title: 'Configure Gradle for Firebase',
    whyThisMatters: 'Gradle needs Firebase plugin and configuration for release builds.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Verify apps/mobile/android/build.gradle has:',
      '  - google-services classpath in buildscript dependencies',
      '  - Firebase BOM in dependencies',
      '',
      'Verify apps/mobile/android/app/build.gradle has:',
      '  - google-services plugin applied',
      '  - Firebase dependencies in implementation',
      '  - signingConfigs for release builds',
      '',
      'Verify apps/mobile/android/gradle.properties.local exists with:',
      '  - MYAPP_RELEASE_STORE_FILE',
      '  - MYAPP_RELEASE_KEY_ALIAS',
      '  - MYAPP_RELEASE_STORE_PASSWORD',
      '  - MYAPP_RELEASE_KEY_PASSWORD',
    ],
    scripts: [
      {
        label: 'Check Gradle build configuration',
        command: 'cd apps/mobile/android && grep -n "google-services\|firebase" build.gradle app/build.gradle || echo "Check manually"',
      },
      {
        label: 'Check gradle properties',
        command: 'ls -la apps/mobile/android/gradle.properties.local',
      },
    ],
  },
  {
    id: 'm-staging-action-build-android',
    platform: 'mobile',
    environment: 'staging',
    title: 'Build Android release bundle',
    whyThisMatters: 'Single production build works for both staging and production via runtime switch.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Build Android AAB for production:',
      '  cd apps/mobile',
      '  bash scripts/build-android.sh production',
      '',
      'This creates a single build that can switch between environments',
      'The build will be saved to: apps/mobile/dist/android/production/',
    ],
    scripts: [
      {
        label: 'Build Android bundle',
        command: 'cd apps/mobile && bash scripts/build-android.sh production',
      },
    ],
  },
  {
    id: 'm-staging-verify-build',
    platform: 'mobile',
    environment: 'staging',
    title: 'Verify staging build and deployment',
    whyThisMatters: 'Confirms the build works and can switch to staging at runtime.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Install the AAB on a device or use Internal Testing track:',
      '  - Upload to Google Play Console → Internal Testing',
      '  - Add testers and install from Play Store link',
      '',
      'Test environment switching:',
      '  - Open app and go to Profile screen',
      '  - Tap version text 7 times to enable Developer Options',
      '  - Toggle "Use Staging Environment" switch',
      '  - Verify STAGE badge appears in top-right',
      '  - Test app functionality with staging backend',
    ],
    scripts: [
      {
        label: 'Verify staging doctor',
        command: 'node common/scripts/doctor.js staging --non-interactive',
      },
    ],
    expected: ['Firebase project configured', 'Build successful', 'Environment switching works'],
  },

  // Production Section - Comprehensive Firebase Production Setup
  {
    id: 'm-production-action-prerequisites',
    platform: 'mobile',
    environment: 'production',
    title: 'Production Prerequisites Check',
    whyThisMatters: 'Ensure all requirements are met before production setup.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Verify you have:',
      '  - Google Play Console access ($25 one-time fee paid)',
      '  - Apple Developer Account ($99/year, optional for Android-only)',
      '  - Android release keystore created and backed up',
      '  - Staging environment fully working',
      '  - All features tested and working in staging',
      '',
      'Never use production for testing!',
    ],
    scripts: [
      {
        label: 'Check prerequisites',
        command: 'echo "Verify: Play Console access, keystore backup, staging working"',
      },
    ],
  },
  {
    id: 'm-production-action-firebase-project',
    platform: 'mobile',
    environment: 'production',
    title: 'Create Firebase production project',
    whyThisMatters: 'Production needs a separate Firebase project to isolate live user data.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Go to Firebase Console: https://console.firebase.google.com/',
      'Click "Add project" and name it: traxettle-prod',
      'Enable Google Analytics (recommended for production)',
      'Click "Create project" and wait for provisioning',
      'Note the Project ID (should be: traxettle-prod)',
      '',
      'IMPORTANT: This will handle real user data!',
    ],
    scripts: [
      {
        label: 'Check Firebase project ID',
        command: 'echo "Expected Firebase project ID: traxettle-prod"',
      },
    ],
  },
  {
    id: 'm-production-action-firebase-services',
    platform: 'mobile',
    environment: 'production',
    title: 'Enable Firebase production services',
    whyThisMatters: 'Production services need proper configuration for live users.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-prod project, enable Authentication:',
      '  - Go to Authentication → Sign-in method',
      '  - Enable Email/Password provider',
      '  - Enable Google provider (requires OAuth consent screen)',
      '',
      'Enable Firestore Database:',
      '  - Go to Firestore Database → Create database',
      '  - Choose Start in production mode',
      '  - Select a location (choose nearest to your users)',
      '  - Configure security rules (start locked down)',
      '',
      'Enable Storage:',
      '  - Go to Storage → Get started',
      '  - Choose Start in production mode',
      '  - Configure security rules (start locked down)',
    ],
    scripts: [
      {
        label: 'Check Firebase services enabled',
        command: 'echo "Verify Authentication, Firestore, and Storage are enabled in production mode"',
      },
    ],
  },
  {
    id: 'm-production-action-firebase-android',
    platform: 'mobile',
    environment: 'production',
    title: 'Add Android app to Firebase production',
    whyThisMatters: 'Production Android app needs Firebase configuration.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-prod Firebase project:',
      '  - Go to Project Settings → Your Apps',
      '  - Click Android icon to add Android app',
      '  - Package name: com.traxettle.app (same as staging)',
      '  - Download google-services.json',
      '  - Save as: apps/mobile/android/app/google-services.prod.json',
      '  - DO NOT overwrite staging config yet',
    ],
    scripts: [
      {
        label: 'Check production Android config',
        command: 'ls -la apps/mobile/android/app/google-services.prod.json',
      },
    ],
  },
  {
    id: 'm-production-action-firebase-ios',
    platform: 'mobile',
    environment: 'production',
    title: 'Add iOS app to Firebase production',
    whyThisMatters: 'Production iOS app needs Firebase configuration.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-prod Firebase project:',
      '  - Go to Project Settings → Your Apps',
      '  - Click iOS icon to add iOS app',
      '  - Bundle ID: com.traxettle.app (same as staging)',
      '  - Download GoogleService-Info.plist',
      '  - Save as: apps/mobile/GoogleService-Info.prod.plist',
      '  - DO NOT overwrite staging config yet',
    ],
    scripts: [
      {
        label: 'Check production iOS config',
        command: 'ls -la apps/mobile/GoogleService-Info.prod.plist',
      },
    ],
  },
  {
    id: 'm-production-action-firebase-sha',
    platform: 'mobile',
    environment: 'production',
    title: 'Add SHA-1 to Firebase production',
    whyThisMatters: 'Production Firebase needs SHA-1 for release builds.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Use the same SHA-1 from your keystore:',
      '  cd apps/mobile/android/app',
      '  keytool -list -v -keystore traxettle-release-key.keystore -alias traxettle',
      '',
      'In Firebase Console (traxettle-prod):',
      '  - Go to Project Settings → Your Apps → Android app',
      '  - Scroll down to "SHA certificate fingerprints"',
      '  - Click "Add certificate"',
      '  - Paste your SHA-1 fingerprint',
      '  - Save changes',
    ],
    scripts: [
      {
        label: 'Generate SHA-1 from keystore',
        command: 'cd apps/mobile/android/app && keytool -list -v -keystore traxettle-release-key.keystore -alias traxettle | grep SHA1',
      },
    ],
  },
  {
    id: 'm-production-action-apple-team',
    platform: 'mobile',
    environment: 'production',
    title: 'Set up Apple Team ID (if supporting iOS)',
    whyThisMatters: 'Apple Team ID is required for iOS distribution and push notifications.',
    kind: 'action',
    skippable: true,
    instructions: [
      'If you have Apple Developer Account:',
      '  - Go to https://developer.apple.com/account/',
      '  - Sign in and click "Membership" in sidebar',
      '  - Find your "Team ID" (10-character string)',
      '  - Example: AB12CD34EF',
      '',
      'Add Team ID to both Firebase projects:',
      '  - traxettle-staging → Project Settings → Your Apps → iOS app',
      '  - traxettle-prod → Project Settings → Your Apps → iOS app',
      '  - Use the SAME Team ID in both projects',
    ],
    scripts: [
      {
        label: 'Check Apple Team ID setup',
        command: 'echo "If supporting iOS: Add Team ID to both Firebase projects"',
      },
    ],
  },
  {
    id: 'm-production-action-service-account',
    platform: 'mobile',
    environment: 'production',
    title: 'Create Firebase production service account',
    whyThisMatters: 'Production service account allows backend to access live Firebase services.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-prod Firebase project:',
      '  - Go to Project Settings → Service accounts',
      '  - Click "Generate new private key"',
      '  - Select JSON key type',
      '  - Click "Create" and download the JSON file',
      '  - Save as: apps/api/traxettle-prod-service-account.json',
      '  - Never commit this file to version control',
      '  - Store securely (password manager, encrypted storage)',
    ],
    scripts: [
      {
        label: 'Check production service account',
        command: 'ls -la apps/api/traxettle-prod-service-account.json',
      },
    ],
  },
  {
    id: 'm-production-action-api-deployment',
    platform: 'mobile',
    environment: 'production',
    title: 'Deploy API to production (automated)',
    whyThisMatters: 'Production API serves live user requests. This script handles everything automatically.',
    kind: 'action',
    skippable: false,
    instructions: [
      'The deployment script handles everything automatically:',
      '  - Sets up GCP project and services',
      '  - Creates service accounts and permissions',
      '  - Deploys API to Cloud Run',
      '  - Configures secrets and environment variables',
      '',
      'Before running:',
      '  1. Edit scripts/api-deployment/deploy-prod.sh',
      '  2. Fill in all CHANGE_ME placeholders at the top',
      '  3. Create smtp_prod.local.properties from example',
      '  4. Run the deployment script',
    ],
    scripts: [
      {
        label: 'Deploy production API',
        command: 'bash scripts/api-deployment/deploy-prod-gmail.sh',
      },
      {
        label: 'Check API health',
        command: 'curl -f https://traxettle-api-prod-943648574702.us-central1.run.app/health || echo "API not deployed yet"',
      },
    ],
  },
  {
    id: 'm-production-action-security-rules',
    platform: 'mobile',
    environment: 'production',
    title: 'Configure production security rules',
    whyThisMatters: 'Security rules protect production data and prevent unauthorized access.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Firestore Security Rules (traxettle-prod):',
      '  - Go to Firestore Database → Rules',
      '  - Replace test rules with production rules',
      '  - Ensure users can only access their own data',
      '  - Require authentication for all operations',
      '',
      'Storage Security Rules (traxettle-prod):',
      '  - Go to Storage → Rules',
      '  - Replace test rules with production rules',
      '  - Ensure users can only access their own files',
      '  - Validate file types and sizes',
    ],
    scripts: [
      {
        label: 'Check security rules status',
        command: 'echo "Verify security rules are locked down in Firebase Console"',
      },
    ],
  },
  {
    id: 'm-production-action-build-final',
    platform: 'mobile',
    environment: 'production',
    title: 'Build final production APK/AAB',
    whyThisMatters: 'Production build uses production Firebase configuration.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Switch to production Firebase config:',
      '  cd apps/mobile/android/app',
      '  cp google-services.prod.json google-services.json',
      '',
      'Build production AAB:',
      '  cd apps/mobile',
      '  bash scripts/build-android.sh production',
      '',
      'The build will connect to production Firebase by default',
      'Users can switch to staging via 7-tap Developer Options',
    ],
    scripts: [
      {
        label: 'Build production AAB',
        command: 'cd apps/mobile && bash scripts/build-android.sh production',
      },
    ],
  },
  {
    id: 'm-production-action-play-console',
    platform: 'mobile',
    environment: 'production',
    title: 'Set up Google Play Console',
    whyThisMatters: 'Play Console is where you publish the app to Google Play Store.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Create app listing in Google Play Console:',
      '  - Go to https://play.google.com/console',
      '  - Click "Create app"',
      '  - Select app category and fill details',
      '  - Complete store listing (screenshots, description, etc.)',
      '',
      'Set up content rating:',
      '  - Complete content rating questionnaire',
      '  - Submit for rating approval',
      '',
      'Configure pricing and distribution:',
      '  - Set app as paid/free',
      '  - Select countries for distribution',
    ],
    scripts: [
      {
        label: 'Check Play Console setup',
        command: 'echo "Verify app is created in Google Play Console with store listing"',
      },
    ],
  },
  {
    id: 'm-production-action-upload-bundle',
    platform: 'mobile',
    environment: 'production',
    title: 'Upload production bundle to Play Console',
    whyThisMatters: 'Upload the signed AAB for Google Play review and distribution.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Upload production AAB:',
      '  - In Play Console, go to "Release" → "Production"',
      '  - Click "Create new release"',
      '  - Upload your AAB file from apps/mobile/dist/android/production/',
      '  - Fill release notes',
      '  - Set rollout percentage (start with 1-5%)',
      '',
      'Wait for Google Play review:',
      '  - Review typically takes 1-3 days',
      '  - Fix any policy violations if rejected',
    ],
    scripts: [
      {
        label: 'Check production AAB exists',
        command: 'ls -la apps/mobile/dist/android/production/*.aab || echo "Build production AAB first"',
      },
    ],
  },
  {
    id: 'm-production-action-testing',
    platform: 'mobile',
    environment: 'production',
    title: 'Production testing and verification',
    whyThisMatters: 'Thoroughly test production build before public release.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Internal testing (before public release):',
      '  - Use Play Console "Internal Testing" track',
      '  - Add internal testers (your team)',
      '  - Install and test thoroughly',
      '',
      'Test production environment:',
      '  - Verify no STAGE badge (should be production)',
      '  - Test all features with live data',
      '  - Verify authentication works',
      '  - Test subscription flow (if applicable)',
      '',
      'Test staging switch:',
      '  - Enable Developer Options (7 taps)',
      '  - Switch to staging and verify STAGE badge',
      '  - Switch back to production',
    ],
    scripts: [
      {
        label: 'Verify production doctor',
        command: 'node common/scripts/doctor.js production --non-interactive',
      },
    ],
    expected: ['Production build working', 'No STAGE badge', 'All features functional', 'Environment switching works'],
  },
  {
    id: 'm-production-action-launch',
    platform: 'mobile',
    environment: 'production',
    title: 'Launch to public',
    whyThisMatters: 'Make the app available to all users in Google Play Store.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Start production rollout:',
      '  - In Play Console, go to "Release" → "Production"',
      '  - Increase rollout from testing to 100%',
      '  - Or start with staged rollout (10%, 50%, 100%)',
      '',
      'Monitor launch:',
      '  - Watch crash reports in Firebase Crashlytics',
      '  - Monitor performance in Firebase Performance',
      '  - Check user feedback and reviews',
      '  - Be ready to rollback if critical issues found',
    ],
    scripts: [
      {
        label: 'Check launch status',
        command: 'echo "Monitor app performance and user feedback after launch"',
      },
    ],
  },
  {
    id: 'm-production-verify-final',
    platform: 'mobile',
    environment: 'production',
    title: 'Final production verification',
    whyThisMatters: 'Confirm production deployment is successful and stable.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Verify production deployment:',
      '  - App is live in Google Play Store',
      '  - Users can download and install',
      '  - All features work correctly',
      '  - No major crashes or issues',
      '  - Analytics data is flowing',
      '',
      'Ongoing maintenance:',
      '  - Regularly update dependencies',
      '  - Monitor security advisories',
      '  - Keep Firebase service account secure',
      '  - Backup keystore and sensitive data',
    ],
    expected: ['App live in Play Store', 'Users can install', 'All features working', 'Analytics active'],
  },
];
