import type { WorkflowStep } from '@/types';

export const webSteps: WorkflowStep[] = [
  // Prerequisites Section - Must be completed before any environment setup
  {
    id: 'w-prerequisite-system-check',
    platform: 'web',
    environment: 'local', // Show in all environments but mark as local
    title: '🔧 Web Development Requirements',
    whyThisMatters: 'Ensure your system has all required tools for web development.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Verify web development requirements:',
      '  - Node.js 18+ installed',
      '  - npm or yarn package manager',
      '  - Git installed',
      '  - Modern web browser',
      '',
      'Check development tools:',
      '  - Next.js framework working',
      '  - Styled-components configured',
      '  - Build tools working',
    ],
    scripts: [
      {
        label: 'Check Node.js version',
        command: 'node --version',
      },
      {
        label: 'Check npm version',
        command: 'npm --version',
      },
      {
        label: 'Check Git',
        command: 'git --version',
      },
      {
        label: 'Check Next.js',
        command: 'cd apps/web && npx next --version || echo \"Next.js not found\"',
      },
    ],
    expected: ['Node.js 18+', 'npm available', 'Git available', 'Next.js working'],
  },

  // Local Development Section
  {
    id: 'w-local-action-system',
    platform: 'web',
    environment: 'local',
    title: 'Check system requirements',
    whyThisMatters: 'Node.js v24+, Git, and basic tools are required for web development.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Install Node.js v24+ (required by rush.json).',
      'Install Git (for version control).',
      'Install curl/wget (recommended for downloads).',
    ],
    scripts: [
      {
        label: 'Check Node version',
        command: 'node --version',
      },
      {
        label: 'Check Git',
        command: 'git --version',
      },
      {
        label: 'Check curl',
        command: 'curl --version',
      },
    ],
  },
  {
    id: 'w-local-verify-system',
    platform: 'web',
    environment: 'local',
    title: 'Verify system requirements',
    whyThisMatters: 'Ensures your OS and basic tools meet the minimum requirements.',
    kind: 'verify',
    skippable: false,
    instructions: ['Run the doctor script to verify system requirements.'],
    scripts: [
      {
        label: 'Run system checks',
        command: 'node common/scripts/doctor.js local --non-interactive',
      },
    ],
    expected: ['Node.js v24+ detected', 'Git installed', 'curl/wget available'],
  },

  {
    id: 'w-local-action-package-managers',
    platform: 'web',
    environment: 'local',
    title: 'Install package managers',
    whyThisMatters: 'npm, pnpm, and Rush are required to manage monorepo dependencies.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Install npm (comes with Node.js).',
      'Install pnpm (required by Rush).',
      'Verify Rush is working.',
    ],
    scripts: [
      {
        label: 'Check npm',
        command: 'npm --version',
      },
      {
        label: 'Check pnpm',
        command: 'pnpm --version',
      },
      {
        label: 'Check Rush',
        command: 'node common/scripts/install-run-rush.js --version',
      },
    ],
  },
  {
    id: 'w-local-action-install-deps',
    platform: 'web',
    environment: 'local',
    title: 'Install monorepo dependencies',
    whyThisMatters: 'Next.js app needs dependencies installed correctly.',
    kind: 'action',
    skippable: false,
    instructions: ['From the repo root, run the install command and wait for it to finish.'],
    scripts: [{ label: 'Install dependencies', command: 'rush install' }],
  },

  {
    id: 'w-local-action-backend',
    platform: 'web',
    environment: 'local',
    title: 'Set up backend for web',
    whyThisMatters: 'Web app depends on backend API for data and authentication.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Verify backend directory exists',
      'Check backend package.json',
      'Ensure backend dependencies are installed',
    ],
    scripts: [
      {
        label: 'Check backend directory',
        command: 'ls -la apps/api',
      },
      {
        label: 'Check backend dependencies',
        command: 'cd apps/api && npm list --depth=0',
      },
    ],
  },
  {
    id: 'w-local-verify-backend',
    platform: 'web',
    environment: 'local',
    title: 'Verify backend setup',
    whyThisMatters: 'Confirms backend is properly configured for local development.',
    kind: 'verify',
    skippable: false,
    instructions: ['Run the doctor script to verify backend dependencies.'],
    scripts: [
      {
        label: 'Verify backend',
        command: 'node common/scripts/doctor.js local --non-interactive',
      },
    ],
    expected: ['Backend dependencies installed', 'Backend environment configured'],
  },

  {
    id: 'w-local-action-web-deps',
    platform: 'web',
    environment: 'local',
    title: 'Set up web dependencies',
    whyThisMatters: 'Next.js and its dependencies must be installed for the web app.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Verify web directory exists',
      'Check web package.json',
      'Ensure web dependencies are installed',
    ],
    scripts: [
      {
        label: 'Check web directory',
        command: 'ls -la apps/web',
      },
      {
        label: 'Check web dependencies',
        command: 'cd apps/web && npm list --depth=0',
      },
    ],
  },
  {
    id: 'w-local-verify-web-deps',
    platform: 'web',
    environment: 'local',
    title: 'Verify web dependencies',
    whyThisMatters: 'Confirms web app dependencies are properly installed.',
    kind: 'verify',
    skippable: false,
    instructions: ['Run the doctor script to verify web dependencies.'],
    scripts: [
      {
        label: 'Verify web dependencies',
        command: 'node common/scripts/doctor.js local --non-interactive',
      },
    ],
    expected: ['Web dependencies installed', 'Web build configuration valid'],
  },

  {
    id: 'w-local-action-env-vars',
    platform: 'web',
    environment: 'local',
    title: 'Configure environment variables',
    whyThisMatters: 'Environment variables connect the web app to API and services.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Set NEXT_PUBLIC_API_URL for local development',
      'Configure other required environment variables',
      'Create .env.local file if needed',
    ],
    scripts: [
      {
        label: 'Check web env vars',
        command: 'echo "NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL"',
      },
    ],
  },
  {
    id: 'w-local-verify-env-vars',
    platform: 'web',
    environment: 'local',
    title: 'Verify environment variables',
    whyThisMatters: 'Ensures all required environment variables are set.',
    kind: 'verify',
    skippable: false,
    instructions: ['Run the doctor script to verify environment variables.'],
    scripts: [
      {
        label: 'Verify env vars',
        command: 'node common/scripts/doctor.js local --non-interactive',
      },
    ],
    expected: ['Web environment variables configured'],
  },

  {
    id: 'w-local-action-dev-server',
    platform: 'web',
    environment: 'local',
    title: 'Start development server',
    whyThisMatters: 'Run the web app locally to test before deployment.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Start the Next.js development server',
      'Open the app in your browser',
      'Test basic functionality',
    ],
    scripts: [
      {
        label: 'Start web dev server',
        command: 'cd apps/web && npm run dev',
      },
    ],
  },
  {
    id: 'w-local-verify-dev-server',
    platform: 'web',
    environment: 'local',
    title: 'Verify development server',
    whyThisMatters: 'Confirms the web app runs correctly in development mode.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Open http://localhost:3000 in your browser',
      'Verify the home page loads',
      'Test navigation and basic features',
    ],
    expected: ['Development server running', 'Home page loads', 'Navigation works'],
  },

  {
    id: 'w-local-action-final',
    platform: 'web',
    environment: 'local',
    title: 'Final verification',
    whyThisMatters: 'Run comprehensive checks to ensure local environment is ready.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Run the full doctor script',
      'Fix any remaining issues',
      'Test web app locally',
    ],
    scripts: [
      {
        label: 'Run full doctor check',
        command: 'node common/scripts/doctor.js local',
      },
      {
        label: 'Test web build',
        command: 'cd apps/web && npm run build',
      },
    ],
  },

  {
    id: 'w-staging-action-firebase-project',
    platform: 'web',
    environment: 'staging',
    title: 'Create Firebase staging project',
    whyThisMatters: 'Staging web app needs Firebase project for backend services.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Go to Firebase Console: https://console.firebase.google.com/',
      'Click "Add project" and name it: traxettle-staging',
      'Enable Google Analytics (optional)',
      'Click "Create project" and wait for provisioning',
      'Note the Project ID (should be: traxettle-staging)',
    ],
    scripts: [
      {
        label: 'Check Firebase project ID',
        command: 'echo "Expected Firebase project ID: traxettle-staging"',
      },
    ],
  },
  {
    id: 'w-staging-action-firebase-services',
    platform: 'web',
    environment: 'staging',
    title: 'Enable Firebase services for web',
    whyThisMatters: 'Web app needs Firebase services for authentication and data.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-staging project, enable Authentication:',
      '  - Go to Authentication → Sign-in method',
      '  - Enable Email/Password provider',
      '  - Enable Google provider (requires OAuth consent screen)',
      '',
      'Enable Firestore Database:',
      '  - Go to Firestore Database → Create database',
      '  - Choose Start in test mode (for staging)',
      '  - Select a location (choose nearest to your users)',
      '',
      'Add Web app to Firebase:',
      '  - Go to Project Settings → Your Apps',
      '  - Click Web icon to add web app',
      '  - App nickname: Traxettle Web (Staging)',
      '  - Copy Firebase config for web app',
    ],
    scripts: [
      {
        label: 'Check Firebase services enabled',
        command: 'echo "Verify Authentication and Firestore are enabled in Firebase Console"',
      },
    ],
  },
  {
    id: 'w-staging-action-firebase-service-account',
    platform: 'web',
    environment: 'staging',
    title: 'Create Firebase staging service account',
    whyThisMatters: 'Service account allows backend API to access Firebase services.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-staging Firebase project:',
      '  - Go to Project Settings → Service accounts',
      '  - Click "Generate new private key"',
      '  - Select JSON key type',
      '  - Click "Create" and download the JSON file',
      '  - Save as: apps/api/traxettle-staging-service-account.json',
      '  - Never commit this file to version control',
    ],
    scripts: [
      {
        label: 'Check staging service account',
        command: 'ls -la apps/api/traxettle-staging-service-account.json',
      },
    ],
  },
  {
    id: 'w-staging-action-build',
    platform: 'web',
    environment: 'staging',
    title: 'Build web app for staging',
    whyThisMatters: 'Create optimized build for staging deployment.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Build the web app for staging:',
      '  cd apps/web',
      '  npm run build',
      '',
      'Configure staging environment:',
      '  - Set NEXT_PUBLIC_API_URL to staging API',
      '  - Set NEXT_PUBLIC_FIREBASE_CONFIG to staging project',
      '  - Verify build output in .next/ directory',
    ],
    scripts: [
      {
        label: 'Build for staging',
        command: 'cd apps/web && npm run build',
      },
    ],
  },
  {
    id: 'w-staging-action-deploy',
    platform: 'web',
    environment: 'staging',
    title: 'Deploy web app to staging',
    whyThisMatters: 'Deploy the built app to staging environment for testing.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Deploy to staging server:',
      '  - Choose hosting platform (Vercel, Netlify, Railway)',
      '  - Configure environment variables for staging',
      '  - Deploy from .next/ build output',
      '',
      'Environment variables for staging:',
      '  - NEXT_PUBLIC_API_URL: https://traxettle-api-staging-943648574702.us-central1.run.app',
      '  - FIREBASE_SERVICE_ACCOUNT: ./traxettle-staging-service-account.json',
      '  - NODE_ENV: production',
    ],
    scripts: [
      {
        label: 'Verify staging deployment',
        command: 'curl -f https://staging.traxettle.com || echo "Staging site not deployed yet"',
      },
    ],
  },
  {
    id: 'w-staging-verify-deploy',
    platform: 'web',
    environment: 'staging',
    title: 'Verify staging deployment',
    whyThisMatters: 'Ensures staging deployment works correctly.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Test staging web app:',
      '  - Open staging URL in browser',
      '  - Test user registration and login',
      '  - Test all major features',
      '  - Verify API connectivity to staging backend',
      '  - Check Firebase integration',
    ],
    expected: ['Staging site accessible', 'Features working', 'API connected to staging', 'Firebase working'],
  },

  // Production Section - Comprehensive Web Production Setup
  {
    id: 'w-production-action-firebase-project',
    platform: 'web',
    environment: 'production',
    title: 'Create Firebase production project',
    whyThisMatters: 'Production web app needs separate Firebase project for live data.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Go to Firebase Console: https://console.firebase.google.com/',
      'Click "Add project" and name it: traxettle-prod',
      'Enable Google Analytics (recommended for production)',
      'Click "Create project" and wait for provisioning',
      'Note the Project ID (should be: traxettle-prod)',
      '',
      'IMPORTANT: This will handle real user data!',
    ],
    scripts: [
      {
        label: 'Check Firebase project ID',
        command: 'echo "Expected Firebase project ID: traxettle-prod"',
      },
    ],
  },
  {
    id: 'w-production-action-firebase-services',
    platform: 'web',
    environment: 'production',
    title: 'Enable Firebase production services for web',
    whyThisMatters: 'Production web app needs Firebase services for live users.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-prod project, enable Authentication:',
      '  - Go to Authentication → Sign-in method',
      '  - Enable Email/Password provider',
      '  - Enable Google provider (requires OAuth consent screen)',
      '',
      'Enable Firestore Database:',
      '  - Go to Firestore Database → Create database',
      '  - Choose Start in production mode',
      '  - Select a location (choose nearest to your users)',
      '  - Configure security rules (start locked down)',
      '',
      'Add Web app to Firebase:',
      '  - Go to Project Settings → Your Apps',
      '  - Click Web icon to add web app',
      '  - App nickname: Traxettle Web (Production)',
      '  - Copy Firebase config for web app',
    ],
    scripts: [
      {
        label: 'Check Firebase services enabled',
        command: 'echo "Verify Authentication and Firestore are enabled in production mode"',
      },
    ],
  },
  {
    id: 'w-production-action-firebase-service-account',
    platform: 'web',
    environment: 'production',
    title: 'Create Firebase production service account',
    whyThisMatters: 'Production service account allows backend to access live Firebase services.',
    kind: 'action',
    skippable: false,
    instructions: [
      'In traxettle-prod Firebase project:',
      '  - Go to Project Settings → Service accounts',
      '  - Click "Generate new private key"',
      '  - Select JSON key type',
      '  - Click "Create" and download the JSON file',
      '  - Save as: apps/api/traxettle-prod-service-account.json',
      '  - Never commit this file to version control',
      '  - Store securely (password manager, encrypted storage)',
    ],
    scripts: [
      {
        label: 'Check production service account',
        command: 'ls -la apps/api/traxettle-prod-service-account.json',
      },
    ],
  },
  {
    id: 'w-production-action-api-deployment',
    platform: 'web',
    environment: 'production',
    title: 'Deploy API to production (automated)',
    whyThisMatters: 'Production API serves live user requests. This script handles everything automatically.',
    kind: 'action',
    skippable: false,
    instructions: [
      'The deployment script handles everything automatically:',
      '  - Sets up GCP project and services',
      '  - Creates service accounts and permissions',
      '  - Deploys API to Cloud Run',
      '  - Configures secrets and environment variables',
      '',
      'Before running:',
      '  1. Edit scripts/api-deployment/deploy-prod.sh',
      '  2. Fill in all CHANGE_ME placeholders at the top',
      '  3. Create smtp_prod.local.properties from example',
      '  4. Run the deployment script',
    ],
    scripts: [
      {
        label: 'Deploy production API',
        command: 'bash scripts/api-deployment/deploy-prod-gmail.sh',
      },
      {
        label: 'Check API health',
        command: 'curl -f https://traxettle-api-prod-943648574702.us-central1.run.app/health || echo "API not deployed yet"',
      },
    ],
  },
  {
    id: 'w-production-action-security-rules',
    platform: 'web',
    environment: 'production',
    title: 'Configure production security rules',
    whyThisMatters: 'Security rules protect production data and prevent unauthorized access.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Firestore Security Rules (traxettle-prod):',
      '  - Go to Firestore Database → Rules',
      '  - Replace test rules with production rules',
      '  - Ensure users can only access their own data',
      '  - Require authentication for all operations',
      '',
      'Web app security considerations:',
      '  - Enable HTTPS only',
      '  - Set proper CORS headers',
      '  - Validate all user inputs',
      '  - Use environment variables for secrets',
    ],
    scripts: [
      {
        label: 'Check security rules status',
        command: 'echo "Verify security rules are locked down in Firebase Console"',
      },
    ],
  },
  {
    id: 'w-production-action-build',
    platform: 'web',
    environment: 'production',
    title: 'Build web app for production',
    whyThisMatters: 'Create optimized build for production deployment.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Build the web app for production:',
      '  cd apps/web',
      '  npm run build',
      '',
      'Configure production environment:',
      '  - Set NEXT_PUBLIC_API_URL to production API',
      '  - Set NEXT_PUBLIC_FIREBASE_CONFIG to production project',
      '  - Verify build output in .next/ directory',
      '  - Test build locally if possible',
    ],
    scripts: [
      {
        label: 'Build for production',
        command: 'cd apps/web && npm run build',
      },
    ],
  },
  {
    id: 'w-production-action-deploy',
    platform: 'web',
    environment: 'production',
    title: 'Deploy web app to production',
    whyThisMatters: 'Deploy the built app to production for live users.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Deploy to production server:',
      '  - Choose hosting platform (Vercel, Netlify, Railway)',
      '  - Configure environment variables for production',
      '  - Deploy from .next/ build output',
      '',
      'Environment variables for production:',
      '  - NEXT_PUBLIC_API_URL: https://traxettle-api-prod-943648574702.us-central1.run.app',
      '  - FIREBASE_SERVICE_ACCOUNT: ./traxettle-prod-service-account.json',
      '  - NODE_ENV: production',
      '',
      'Set up custom domain (optional):',
      '  - Configure DNS records',
      '  - Set up SSL certificate',
      '  - Test domain resolution',
    ],
    scripts: [
      {
        label: 'Verify production deployment',
        command: 'curl -f https://traxettle.com || echo "Production site not deployed yet"',
      },
    ],
  },
  {
    id: 'w-production-action-monitoring',
    platform: 'web',
    environment: 'production',
    title: 'Set up production monitoring',
    whyThisMatters: 'Monitoring helps you track performance and issues in production.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Set up Firebase Analytics:',
      '  - Verify analytics data is flowing',
      '  - Create dashboards for key metrics',
      '',
      'Set up error tracking:',
      '  - Configure error reporting',
      '  - Set up alerts for critical errors',
      '',
      'Set up performance monitoring:',
      '  - Enable Firebase Performance Monitoring',
      '  - Track page load times',
      '  - Monitor API response times',
    ],
    scripts: [
      {
        label: 'Check monitoring setup',
        command: 'echo "Verify Analytics and Performance monitoring are active in Firebase Console"',
      },
    ],
  },
  {
    id: 'w-production-verify-deploy',
    platform: 'web',
    environment: 'production',
    title: 'Verify production deployment',
    whyThisMatters: 'Ensures production deployment works correctly.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Test production web app thoroughly:',
      '  - Open production URL in browser',
      '  - Test user registration and login',
      '  - Test all major features with live data',
      '  - Verify API connectivity to production backend',
      '  - Check Firebase integration',
      '  - Test responsive design on mobile',
      '  - Verify security (HTTPS, no console errors)',
    ],
    expected: ['Production site accessible', 'Features working', 'API connected to production', 'Firebase working', 'Performance acceptable'],
  },
  {
    id: 'w-production-action-launch',
    platform: 'web',
    environment: 'production',
    title: 'Launch to public',
    whyThisMatters: 'Make the web app available to all users.',
    kind: 'action',
    skippable: false,
    instructions: [
      'Prepare for public launch:',
      '  - Test all user flows end-to-end',
      '  - Prepare documentation and help content',
      '  - Set up user support channels',
      '',
      'Launch the web app:',
      '  - Remove any password protection if used',
      '  - Announce launch to users',
      '  - Monitor traffic and performance',
      '  - Be ready to handle user feedback',
    ],
    scripts: [
      {
        label: 'Check launch status',
        command: 'echo "Monitor web app performance and user feedback after launch"',
      },
    ],
  },
  {
    id: 'w-production-verify-final',
    platform: 'web',
    environment: 'production',
    title: 'Final production verification',
    whyThisMatters: 'Confirm production deployment is successful and stable.',
    kind: 'verify',
    skippable: false,
    instructions: [
      'Verify production deployment success:',
      '  - Web app is live and accessible',
      '  - All features work correctly',
      '  - No major errors or issues',
      '  - Analytics data is flowing',
      '  - Performance is acceptable',
      '',
      'Ongoing maintenance:',
      '  - Regularly update dependencies',
      '  - Monitor security advisories',
      '  - Keep Firebase service account secure',
      '  - Backup data regularly',
    ],
    expected: ['Web app live', 'Users can access', 'All features working', 'Analytics active', 'Performance good'],
  },
];
